export enum IPC_EVENT {
  APP = 'app',
  APPS = 'apps',
  SELECT_DIRECTORY = 'select-directory',
  CREATE_APP = 'create-app',
  UPDATE_APP = 'update-app',
  DELETE_APP = 'delete-app',
  DELETE_APPS = 'delete-apps',
  START_APP = 'start-app',
  START_APPS = 'start-apps',
  STOP_APP = 'stop-app',
  STOP_APPS = 'stop-apps',
  OPEN_OUTPUT_WINDOW = 'open-output-window',
  OUTPUT = 'output',
  GET_ALL_OUTPUT = 'get-all-output',
  DELETE_APP_OUTPUT = 'delete-app-output',
  OPEN_DIRECTORY = 'open-directory',
}
